<?php

namespace Modules\Product\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Product\Models\Collection;
use Modules\Product\Models\Category;
use Modules\Product\Models\Product;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'mens_shirts' => Category::firstWhere(['category' => 'رجالي', 'subcategory' => 'قمصان']),
            'mens_pants' => Category::firstWhere(['category' => 'رجالي', 'subcategory' => 'بناطيل']),
            'mens_jackets' => Category::firstWhere(['category' => 'رجالي', 'subcategory' => 'جواكت']),
            'mens_tshirts' => Category::firstWhere(['category' => 'رجالي', 'subcategory' => 'تيشيرتات']),
            'mens_shorts' => Category::firstWhere(['category' => 'رجالي', 'subcategory' => 'سراويل قصيرة']),
            'mens_underwear' => Category::firstWhere(['category' => 'رجالي', 'subcategory' => 'ملابس داخلية']),
            'womens_dresses' => Category::firstWhere(['category' => 'حريمي', 'subcategory' => 'فساتين']),
            'womens_blouses' => Category::firstWhere(['category' => 'حريمي', 'subcategory' => 'بلوزات']),
            'womens_skirts' => Category::firstWhere(['category' => 'حريمي', 'subcategory' => 'تنانير']),
            'womens_pants' => Category::firstWhere(['category' => 'حريمي', 'subcategory' => 'بناطيل']),
            'womens_underwear' => Category::firstWhere(['category' => 'حريمي', 'subcategory' => 'ملابس داخلية']),
            'boys' => Category::firstWhere(['category' => 'أطفال', 'subcategory' => 'أولاد']),
            'girls' => Category::firstWhere(['category' => 'أطفال', 'subcategory' => 'بنات']),
            'babies' => Category::firstWhere(['category' => 'أطفال', 'subcategory' => 'رضع']),
            'accessories' => Category::firstWhere(['category' => 'إكسسوارات', 'subcategory' => null]),
            'bags' => Category::firstWhere(['category' => 'إكسسوارات', 'subcategory' => 'حقائب']),
            'jewelry' => Category::firstWhere(['category' => 'إكسسوارات', 'subcategory' => 'مجوهرات']),
            'sunglasses' => Category::firstWhere(['category' => 'إكسسوارات', 'subcategory' => 'نظارات']),
        ];

        $collections = [
            'new_arrivals' => Collection::firstWhere('title', 'وصلنا حديثاً'),
            'formal_men' => Collection::firstWhere('title', 'رجالي - رسمي'),
            'casual_men' => Collection::firstWhere('title', 'رجالي - كاجوال'),
            'sports_men' => Collection::firstWhere('title', 'رجالي - رياضي'),
            'winter_women' => Collection::firstWhere('title', 'حريمي - شتوي'),
            'summer_women' => Collection::firstWhere('title', 'حريمي - صيفي'),
            'formal_women' => Collection::firstWhere('title', 'حريمي - رسمي'),
            'new_kids' => Collection::firstWhere('title', 'أطفال - جديد'),
            'casual_kids' => Collection::firstWhere('title', 'أطفال - كاجوال'),
            'school_kids' => Collection::firstWhere('title', 'أطفال - مدرسي'),
            'accessories' => Collection::firstWhere('title', 'إكسسوارات'),
            'luxury_accessories' => Collection::firstWhere('title', 'إكسسوارات - فاخرة'),
            'special_offers' => Collection::firstWhere('title', 'عروض خاصة'),
            'spring_seasonal' => Collection::firstWhere('title', 'موسمي - ربيع'),
            'fall_seasonal' => Collection::firstWhere('title', 'موسمي - خريف'),
        ];

        $products = [
            // Men's Shirts
            [
                'name' => 'قميص كتان فاخر',
                'category_id' => $categories['mens_shirts']->id,
                'collection_id' => $collections['new_arrivals']->id,
                'tags' => ['linen', 'menswear', 'classic'],
                'price' => 850,
                'fabric' => 'كتان فائق الجودة',
                'notes' => 'قميص مريح وناعم مع لمسة فاخرة.',
                'image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'قميص قطن رسمي',
                'category_id' => $categories['mens_shirts']->id,
                'collection_id' => $collections['formal_men']->id,
                'tags' => ['cotton', 'formal', 'menswear'],
                'price' => 750,
                'fabric' => 'قطن 100%',
                'notes' => 'قميص رسمي مثالي للمناسبات المهنية.',
                'image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'قميص بولو كلاسيك',
                'category_id' => $categories['mens_shirts']->id,
                'collection_id' => $collections['casual_men']->id,
                'tags' => ['polo', 'casual', 'menswear'],
                'price' => 550,
                'fabric' => 'قطن مع نسبة إيلاستين',
                'notes' => 'قميص بولو مريح للاستخدام اليومي.',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
                'status' => 'show',
            ],
            // Men's Pants
            [
                'name' => 'بنطال تشينو كلاسيك',
                'category_id' => $categories['mens_pants']->id,
                'collection_id' => $collections['casual_men']->id,
                'tags' => ['pants', 'menswear', 'casual'],
                'price' => 1200,
                'fabric' => 'قطن مع نسبة إيلاستين',
                'notes' => 'بنطال يومي مريح يناسب الاطلالات كاجوال.',
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'بنطال جينز رسمي',
                'category_id' => $categories['mens_pants']->id,
                'collection_id' => $collections['formal_men']->id,
                'tags' => ['jeans', 'formal', 'menswear'],
                'price' => 1400,
                'fabric' => 'دينم فاخر',
                'notes' => 'جينز بقصة مستقيمة مناسب للمكاتب.',
                'image' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
                'status' => 'show',
            ],
            // Men's Jackets
            [
                'name' => 'جاكيت عصري',
                'category_id' => $categories['mens_jackets']->id,
                'collection_id' => $collections['new_arrivals']->id,
                'tags' => ['jacket', 'menswear', 'winter'],
                'price' => 1650,
                'fabric' => 'صوف مخلوط',
                'notes' => 'جاكيت أنيق للأجواء الباردة.',
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'جاكيت رياضي',
                'category_id' => $categories['mens_jackets']->id,
                'collection_id' => $collections['sports_men']->id,
                'tags' => ['jacket', 'sports', 'menswear'],
                'price' => 950,
                'fabric' => 'بوليستر عالي الأداء',
                'notes' => 'جاكيت رياضي مريح وخفيف الوزن.',
                'image' => 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400',
                'status' => 'show',
            ],
            // Men's T-shirts
            [
                'name' => 'تيشيرت قطن أساسي',
                'category_id' => $categories['mens_tshirts']->id,
                'collection_id' => $collections['casual_men']->id,
                'tags' => ['tshirt', 'cotton', 'basic'],
                'price' => 350,
                'fabric' => 'قطن ناعم 100%',
                'notes' => 'تيشيرت يومي لا غنى عنه.',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
                'status' => 'show',
            ],
            // Men's Shorts
            [
                'name' => 'سروال قصير رياضي',
                'category_id' => $categories['mens_shorts']->id,
                'collection_id' => $collections['sports_men']->id,
                'tags' => ['shorts', 'sports', 'menswear'],
                'price' => 450,
                'fabric' => 'ألياف صناعية مريحة',
                'notes' => 'مثالي للجري والتمارين الرياضية.',
                'image' => 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400',
                'status' => 'show',
            ],
            // Women's Dresses
            [
                'name' => 'فستان سهرة حرير',
                'category_id' => $categories['womens_dresses']->id,
                'collection_id' => $collections['formal_women']->id,
                'tags' => ['dress', 'silk', 'formal'],
                'price' => 2200,
                'fabric' => 'حرير طبيعي',
                'notes' => 'فستان أنيق للمناسبات الخاصة.',
                'image' => 'https://images.unsplash.com/photo-1539008835270-386616781283?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'فستان صيفي خفيف',
                'category_id' => $categories['womens_dresses']->id,
                'collection_id' => $collections['summer_women']->id,
                'tags' => ['dress', 'summer', 'casual'],
                'price' => 1200,
                'fabric' => 'شيفون ناعم',
                'notes' => 'فستان مريح للنزهات الصيفية.',
                'image' => 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400',
                'status' => 'show',
            ],
            // Women's Blouses
            [
                'name' => 'بلوزة حرير ناعمة',
                'category_id' => $categories['womens_blouses']->id,
                'collection_id' => $collections['new_arrivals']->id,
                'tags' => ['blouse', 'silk', 'womenswear'],
                'price' => 950,
                'fabric' => 'ساتان حريري',
                'notes' => 'بلوزة فاخرة تناسب العمل والسهرات.',
                'image' => 'https://images.unsplash.com/photo-1583496661160-fb5886a6aaaa?w=400',
                'status' => 'show',
            ],
            // Women's Skirts
            [
                'name' => 'تنورة قصيرة عصرية',
                'category_id' => $categories['womens_skirts']->id,
                'collection_id' => $collections['summer_women']->id,
                'tags' => ['skirt', 'womenswear', 'casual'],
                'price' => 650,
                'fabric' => 'بوليستر مخلوط',
                'notes' => 'تنورة أنيقة بتصميم عصري.',
                'image' => 'https://images.unsplash.com/photo-1583496661160-fb5886a6aaaa?w=400',
                'status' => 'show',
            ],
            // Women's Pants
            [
                'name' => 'بنطال نسائي أنيق',
                'category_id' => $categories['womens_pants']->id,
                'collection_id' => $collections['formal_women']->id,
                'tags' => ['pants', 'formal', 'womenswear'],
                'price' => 1100,
                'fabric' => 'قماش فاخر',
                'notes' => 'بنطال رسمي بقصة عصرية.',
                'image' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
                'status' => 'show',
            ],
            // Accessories
            [
                'name' => 'حذاء جلد طبيعي',
                'category_id' => $categories['accessories']->id,
                'collection_id' => $collections['accessories']->id,
                'tags' => ['shoes', 'leather', 'menswear'],
                'price' => 1950,
                'fabric' => 'جلد بقري طبيعي',
                'notes' => 'حذاء متين ومريح يدوم طويلاً.',
                'image' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'حقيبة جلدية فاخرة',
                'category_id' => $categories['bags']->id,
                'collection_id' => $collections['luxury_accessories']->id,
                'tags' => ['bag', 'leather', 'luxury'],
                'price' => 2850,
                'fabric' => 'جلد فاخر مع معادن مطلية',
                'notes' => 'حقيبة يد أنيقة وعملية.',
                'image' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'عقد ذهبي أنيق',
                'category_id' => $categories['jewelry']->id,
                'collection_id' => $collections['luxury_accessories']->id,
                'tags' => ['jewelry', 'gold', 'accessories'],
                'price' => 3200,
                'fabric' => 'ذهب عيار 18',
                'notes' => 'عقد رقيق يضيف لمسة سحرية.',
                'image' => 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'نظارات شمسية عصرية',
                'category_id' => $categories['sunglasses']->id,
                'collection_id' => $collections['accessories']->id,
                'tags' => ['sunglasses', 'accessories', 'luxury'],
                'price' => 850,
                'fabric' => 'إطار معدني مع عدسات مستقطبة',
                'notes' => 'حماية كاملة من أشعة الشمس.',
                'image' => 'https://images.unsplash.com/photo-1511499767390-a73359586733?w=400',
                'status' => 'show',
            ],
            // Kids
            [
                'name' => 'تيشيرت أطفال برسومات',
                'category_id' => $categories['boys']->id,
                'collection_id' => $collections['new_kids']->id,
                'tags' => ['kids', 'tshirt', 'boys'],
                'price' => 450,
                'fabric' => 'قطن ناعم',
                'notes' => 'تيشيرت أطفال مريح برسومات مرحة.',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'بنطال أطفال جينز',
                'category_id' => $categories['boys']->id,
                'collection_id' => $collections['casual_kids']->id,
                'tags' => ['kids', 'jeans', 'boys'],
                'price' => 620,
                'fabric' => 'دينم مرن',
                'notes' => 'بنطال جينز عملي ومتين للعب اليومي.',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'فستان أطفال مطبوع',
                'category_id' => $categories['girls']->id,
                'collection_id' => $collections['new_kids']->id,
                'tags' => ['kids', 'dress', 'girls'],
                'price' => 540,
                'fabric' => 'قماش قطني خفيف',
                'notes' => 'فستان طفولي ملون بمطبوعات جذابة.',
                'image' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'بلوزة أطفال بنقشة زهرية',
                'category_id' => $categories['girls']->id,
                'collection_id' => $collections['casual_kids']->id,
                'tags' => ['kids', 'top', 'girls'],
                'price' => 360,
                'fabric' => 'قطن مع لمسة إيلاستين',
                'notes' => 'بلوزة ناعمة بنقشة زهرية مناسبة للنزهات.',
                'image' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
                'status' => 'show',
            ],
            [
                'name' => 'بدلة رضع مريحة',
                'category_id' => $categories['babies']->id,
                'collection_id' => $collections['new_kids']->id,
                'tags' => ['babies', 'outfit', 'comfort'],
                'price' => 280,
                'fabric' => 'قطن عضوي 100%',
                'notes' => 'بدلة ناعمة جداً لبشرة الرضع.',
                'image' => 'https://images.unsplash.com/photo-1522771930-781902788546?w=400',
                'status' => 'show',
            ],
            // Special Offers
            [
                'name' => 'جاكيت شتوي مخفض',
                'category_id' => $categories['mens_jackets']->id,
                'collection_id' => $collections['special_offers']->id,
                'tags' => ['jacket', 'menswear', 'winter', 'sale'],
                'price' => 1350,
                'fabric' => 'صوف مع بطانة حرارية',
                'notes' => 'فرصة لا تعوض للشتاء.',
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
                'status' => 'show',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
